# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-08-09 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20200803_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='跟进内容')),
                ('status', models.CharField(choices=[('A', '近期无报名计划'), ('B', '1月内报名'), ('C', '2周内报名'), ('D', '1周内报名'), ('E', '交定金'), ('F', '已到班'), ('G', '付全款'), ('H', '无效')], help_text='选择客户此时的状态', max_length=8, verbose_name='跟进状态')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='跟进日期')),
                ('delete_status', models.BooleanField(default=False, verbose_name='删除状态')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Customers', verbose_name='咨询的客户')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='部门')),
                ('count', models.IntegerField(verbose_name='部门人数')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True, verbose_name='报名日期')),
                ('delete_status', models.BooleanField(default=False, verbose_name='删除状态')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('why_us', models.TextField(blank=True, default=None, max_length=1024, null=True, verbose_name='为什么报名')),
                ('your_expectation', models.TextField(blank=True, default=None, max_length=1024, null=True, verbose_name='你的期望')),
                ('contract_agreed', models.BooleanField(default=False, verbose_name='我已认真阅读完培训协议并同意全部协议内容')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Customers', verbose_name='客户名称')),
                ('enrollment_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.ClassList', verbose_name='所属班级')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Campuses', verbose_name='所属学校')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set([('customer', 'enrollment_class')]),
        ),
    ]
